server {
	listen 127.0.0.1:8888;
	server_name site_one;

	client_max_body_size 1M;

	error_page 404 /404.html;
	error_page 405 /4xx.html;
	error_page 412 /4xx.html;

	location / {
		root /websites/site_one;
		index index.html;
		autoindex on;
		return 301 https://media1.tenor.com/m/SSY2V0RrU3IAAAAd/rick-roll-rick-rolled.gif;

		limit_except GET POST DELETE {
			deny all;
		}
	}
	
	location /docs {
		root /websites/site_one;

		limit_except GET {
			deny all;
		}
	}

	location /downloads {
		root /websites/site_one;
		autoindex on;

		limit_except GET {
			deny all;
		}
	}

	location /images {
		root /websites/site_one;
		autoindex on;
		limit_except GET {
			deny all;
		}
	}

	location /upload {
		root /websites/site_one;

		file_uploads yes;
		upload_store /websites/site_one/uploads;

		limit_except POST DELETE {
			deny all;
		}
	}
}

server {
	listen 127.0.0.1:7979;
	server_name http://site_two.com;
	client_max_body_size 1M;
	error_page 404 405 412 /4xx.html;
	location / {
		root /websites/site_two;
		index index.html;
		autoindex on;
		limit_except GET POST DELETE {
			deny all;
		}
	}
	location /upload {
		root /websites/site_two;
		file_uploads yes;
		upload_store /websites/site_two/uploads;
		limit_except POST DELETE {
			deny all;
		}
	}
	location /images {
		root /websites/site_two;
		limit_except GET {
			deny all;
		}
	}
    location /cgi-bin {
        limit_except GET POST DELETE {
			deny all;
		}
        #index test.py;
        cgi on;
        autoindex on;
    }
}