server {
	listen 127.0.0.1:8888;
	client_max_body_size 1M;
	error_page 404 405 412 /4xx.html;
	location / {
		root /var/www/html;
		index index.html;
		autoindex on;
	}
	location .php {
		root /cgi-bin;
		fastcgi_param SCRIPT_FILENAME
		fastcgi_param QUERY_STRING
		fastcgi_param REQUEST_METHOD
		fastcgi_param CONTENT_TYPE
		fastcgi_param CONTENT_LENGTH
		fastcgi_param PATH_INFO
	}
}