server {
	listen 127.0.0.1:6969;
	server_name http://website_1.com;

	client_max_body_size 1M;

	error_page 404 /4xx.html;
	error_page 405 /4xx.html;
	error_page 412 /4xx.html;

	location / {
		root /websites/website_1;
		index index.html;
		autoindex on;

		limit_except GET POST DELETE {
			deny all;
		}
	}

	location /downloads {
		root /websites/website_1;
		autoindex on;

		limit_except GET {
			deny all;
		}
	}

	location /images {
		root /websites/website_1;

		limit_except GET {
			deny all;
		}
	}

	location /random {
		root /websites/website_1;
		autoindex on;

		limit_except GET {
			deny all;
		}
	}

	location /uploads1 {
		root /websites/website_1;

		file_uploads yes;
		upload_store /websites/website_1/uploads1;
		autoindex on;

		limit_except GET POST DELETE {
			deny all;
		}
	}

	location /uploads {
		root /websites/website_1;

		file_uploads yes;
		upload_store /websites/website_1/uploads;
		autoindex on;

		limit_except GET POST DELETE {
			deny all;
		}
	}

	location /cgi-bin {
		root /websites/website_1;
        limit_except GET POST DELETE {
			deny all;
		}
        cgi on;
        autoindex on;
    }
}

server {
    listen 127.0.0.1:7979;
    server_name website_2.com;

    client_max_body_size 1M;

    error_page 404 /404.html;
    error_page 405 /4xx.html;
    error_page 412 /4xx.html;
    error_page 413 /4xx.html;

    location / {
        root /websites/website_2;
        index index.html;

        limit_except GET {
            deny all;
        }
    }

    location /docs {
        root /websites/website_2;
        index index.html;

        limit_except GET {
            deny all;
        }
    }

    location /downloads {
        root /websites/website_2;
        autoindex on;

        limit_except GET {
            deny all;
        }
    }

    location /images {
        root /websites/website_2;
        autoindex on;

        limit_except GET {
            deny all;
        }
    }

    location /random {
        root /websites/website_2;
        autoindex on;

        limit_except GET {
            deny all;
        }
    }

    location /uploads1 {
        root /websites/website_2;
        file_uploads yes;
        upload_store /websites/website_2/uploads1;
        autoindex on;

        limit_except GET POST DELETE {
            deny all;
        }
    }

    location /uploads {
        root /websites/website_2;
        file_uploads yes;
        upload_store /websites/website_2/uploads;
        autoindex on;

        limit_except GET POST DELETE {
            deny all;
        }
    }

    location /cgi-bin {
        root /websites/website_2;
        cgi on;
        autoindex on;

        limit_except GET POST {
            deny all;
        }
    }
}